sdrc/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

from sdrc import settings

app_name = 'sdrc'

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^request_reimbursement/$', views.request_reimbursement, name='request_reimbursement'),
    url(r'^milestone_list/$', views.milestone_list, name='milestone_list'),
    url(r'^task_list/$', views.task_list, name='task_list'),
    url(r'^member_list/$', views.member_list, name='member_list'),
    url(r'^(?P<id>\d+)/update-budget-plan/$', views.updateBudgetPlan, name='update-budget-plan'),
    url(r'^incidentreport_summary/$', views.incidentreport_summary, name='incidentreport_summary'),
    url(r'^user_list/$', views.user_list, name='user_list'),
    url(r'^projectbudget_overview/$', views.projectbudget_overview, name='projectbudget_overview'),
    url(r'^view_reimbursements/$', views.view_reimbursements, name='view_reimbursements'),
    url(r'^request_cashadvance/$', views.cashadvance, name='cashadvance'),
    url(r'^view_cashadvance/$', views.cashadvance_admin, name='cashadvance_admin'),
    url(r'^request_procurement/$', views.requestprocurement, name='requestprocurement'),
    url(r'^view_procurement/$', views.requestprocurement_admin, name='requestprocurement_admin'),
url(r'^requestbudgetextension/$', views.request_budget_extension, name='request_budget_extension'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^password_reset/complete/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='sdrc/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name='sdrc/login.html'), name='logout'),
    url(r'^create-budget-plan/$', views.create_budget, name='create-budget-plan'),
    url(r'^view-budget-plan/$', views.budget_plan_create, name='create-budget'),
    url(r'^create-expense-tracker/$', views.create_expense_tracker, name='create-expense-tracker'),
    url(r'^create-project-account/$', views.create_project_account, name='create-account'),
    url(r'^adminindex/$', views.AdminIndexView.as_view(), name='adminindex'),
    url(r'^view_reallocation/$', views.view_reallocation, name='adminindex'),
    url(r'^viewpastprojects/$', views.view_past_projects, name='pastprojects'),
    url(r'^systemlocked/$', views.dashboard_locked, name='systemlocked'),
    url(r'^ganttchart/$', views.GanttChartView, name='ganttchart'),
    url(r'^request_final/$', views.request_final, name='request_final'),
    url(r'^addmembers/$', views.add_members, name='addmembers'),
    url(r'^create-budget-details/$', views.create_budget_details, name='create-budget'),
    url(r'^view_projectextension/$', views.projectextension, name='projectextension'),
    url(r'^expensereport/$', views.expense_report, name='expense-report'),
    url(r'^budget-status/$', views.view_budget_status, name='budget-status', ),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^incidentreport/$', views.IncidentReportsView, name='incidentreport'),
    url(r'^createmilestone/$', views.create_project, name='createmilestone'),
    url(r'^resolvedissues/$', views.resolved_issues, name='resolvedissues'),
    url(r'^samplegantt/$', views.SampleGanttView, name='samplegantt'),
    url(r'^budgetextension/$', views.view_budget_extension, name='budgetextension'),
    url(r'^tor-DLSU/$', views.create_term_of_reference_DLSU, name='tor-DLSU'),
    url(r'^piindex/$', views.PIIndexView, name='piindex'),
    url(r'^view-projects/$', views.view_projects, name='view-projects'),
    url(r'^projectcharter/$', views.create_project_charter, name='projectcharter'),
    url(r'^appointmentform/$', views.AppointmentFormView.as_view(), name='appointmentform'),
    url(r'^createincidentreport/$', views.incident_report_post, name='createincidentreport'),
    url(r'^expensetracking/$', views.ExpenseTracking, name='expensetracking'),
    url(r'^(?P<id>\d+)/update-project/$', views.update_project_account, name='update'),
    url(r'^expenselist/$', views.ExpenseListView.as_view(), name='expenselist'),
    url(r'^budgetextensionform/$', views.budget_extension_form, name='budgetextensionform'),
    url(r'^uploadprojectinformation/$', views.UploadProjectInformationView.as_view(), name='uploadprojectinformation'),
    url(r'^milestonestatus/$', views.MilestoneStatusView, name='milestonestatus'),
    url(r'^financialreport/$', views.FinancialReportView.as_view(), name='financialreport'),
    url(r'^viewprojectstatus/$', views.ProjectStatusView.as_view(), name='projectstatus'),
    url(r'^createbudget/$', views.create_budget, name='createbudget'),
    url(r'^projectbudget/$', views.ProjectBudgetView.as_view(), name='projectbudget'),
    url(r'^createtasks/$', views.create_tasks, name='createtask'),
    url(r'^progressreport/$', views.progress_report, name='progressreport'),
    url(r'^accomplishmentreport/$', views.accomplishment_report, name='accomplishmentreport'),
    url(r'^generatereports/$', views.generate_reports, name='generatereports'),
    url(r'^projectcompletion/$', views.project_completion, name='projectcompletion'),
    url(r'^uploadfinalreport/$', views.final_report, name='uploadfinalreport'),
    url(r'^viewcompleteprojects/$', views.complete_projects, name='viewcompleteprojects'),
    url(r'^projectstatus/$', views.project_status, name='projectstatus'),
    url(r'^reportsarchive/$', views.reports_archive, name='reportsarchive'),
url(r'^inventoryrequest/$', views.inventory_report, name='inventoryrequest'),
url(r'^inventoryrequestadmin/$', views.inventory_report_admin, name='inventoryrequestadmin'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.urls import include, path

app_name = 'sdrc'

urlpatterns = [
    path('sdrc/', include('sdrc.urls', namespace='sdrc')),


]

sdrc/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.timezone import now
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver

import datetime


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    active_project = models.BooleanField(default=False)
    principal_investigator = models.BooleanField(default=False)

def __str__(self):
    return self.active_project

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Project(models.Model):
    TRANCHE_CHOICES = (
        ('First Tranche', 'First Tranche'),
        ('Second Tranche', 'Second Tranche'),
        ('Third Tranche', 'Third Tranche'),
        ('Final Tranche', 'Final Tranche')
    )
    accountNumber = models.IntegerField()
    principalInvestigator = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    projectTitle = models.CharField(max_length=1000)
    fundingAgency = models.CharField(max_length=1000)
    progress = models.IntegerField(default=0, null=True)
    projectCost = models.DecimalField(max_digits=12,decimal_places=2)
    nowDate = models.DateField()
    startDate = models.DateField()
    endDate = models.DateField()
    files = models.FileField(null=True, blank=True)
    contractFile = models.FileField(upload_to='files', null=True, blank=True)
    finalReport = models.FileField(upload_to='files', null=True, blank=True)
    dateFinished = models.DateField(null=True, blank=True)
    projectOverview = models.TextField()
    status = models.CharField(max_length=100, default="In Progress")
    dateReceived = models.DateField(null=True)
    budgetSpent = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    budgetRemaining = models.DecimalField(max_digits=20, decimal_places=2, default=projectCost)
    hasTranche=models.BooleanField(default=False, null=True)
    trancheStatus = models.CharField(max_length=100, null=True, blank=True)
    tranche = models.CharField(max_length=100, choices=TRANCHE_CHOICES, null=True, blank=True)
    trancheAmount = models.DecimalField(max_digits=20, decimal_places=2, null=True, default=0.00)
    totalExpense = models.DecimalField(max_digits=20, decimal_places=2,null=True,default=0)
    remarks = models.CharField(max_length=5000, null=True, blank=True)

    def __str__(self):
        return self.projectTitle

    def get_name(self):
        return self.principalInvestigator.first_name + " " + self.principalInvestigator.last_name

    def get_email(self):
        return self.principalInvestigator.email

    def get_daysLeft(self):
        end = self.endDate
        curr = datetime.date.today()
        return (end-curr).days


    def get_strDaysLeft(self):
        end = self.endDate
        curr = datetime.date.today()
        return str(end-curr).split(",")[0]

    def get_contract_file(self):
        return self.contractFile

    def members_as_list(self):
        return self.projectMember.split(',')

    def tranche_as_list(self):
        return self.tranche.split(',')

    def getBudgetSpent(self):
        expense = self.totalExpense
        total = self.trancheAmount
        return total - expense

    def getBudgetStatus(self):
        budget = self.trancheAmount
        remaining = self.budgetRemaining
        status = (remaining / budget ) * 100
        return status

    def getBudgetOverrun(self):
        expense = self.totalExpense
        budget = self.projectCost
        overrun = ((expense - budget)/budget) * 100
        return overrun

    def get_percentage_completed(self):
        if self.task_set.all():
            all_task = self.task_set.all().count()
            completed_task = Task.objects.filter(project=self.id, taskStatus='Completed').count()
            return (completed_task / all_task) * 100
        else:
            return 0

class ProjectMember(models.Model):
    project = models.ForeignKey(Project, default='1', on_delete=models.CASCADE)
    member = models.ForeignKey(User, default='1', on_delete=models.CASCADE)
    email = models.CharField(max_length=100)
    role = models.CharField(max_length=1000)

    def __str__(self):
        return self.role

class Milestone(models.Model):
    project = models.ForeignKey(Project, default='1', on_delete=models.CASCADE)
    milestoneName = models.CharField(max_length=1000, null=False)
    milestonestartDate = models.DateField(blank=True, null=True)
    milestoneendDate = models.DateField(blank=True, null=True)
    milestoneFinished = models.DateField(blank=True, null=True)
    milestoneStatus = models.CharField(max_length=30, default='Not Started')
    trancheAmount = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    nowDate = models.DateField()

    def __str__(self):
        return self.milestoneName

    def get_daysLeft(self):
        end = self.milestoneendDate
        curr = datetime.date.today()
        return (end-curr).days

    def get_finished_task(self):
        if self.task_set.all():
            all_task = self.task_set.all().count()
            completed_task = Task.objects.filter(milestone=self.id, taskStatus='Completed').count()
            return (completed_task/all_task) * 100

    def in_progress_task(self):
        if self.task_set.all():
            return (Task.objects.filter(milestone=self.id, taskStatus='In Progress').count() / self.task_set.all().count()) * 100

    def not_started_task(self):
        if self.task_set.all():
            return (Task.objects.filter(milestone=self.id, taskStatus='Not Started').count() / self.task_set.all().count()) * 100

    def delayed_task(self):
        if self.task_set.all():
            return (Task.objects.filter(milestone=self.id, taskendDate__lt=datetime.date.today(), taskStatus='Not Started').count() + \
               Task.objects.filter(milestone=self.id, taskendDate__lt=datetime.date.today(), taskStatus='In Progress').count()
                / self.task_set.all().count()) * 100

class Task(models.Model):
    project = models.ForeignKey(Project, default='1', on_delete=models.CASCADE)
    milestone = models.ForeignKey(Milestone, default='1', on_delete=models.CASCADE)
    taskName = models.CharField(max_length=1000, null=True)
    assignedTo = models.CharField(max_length=30, null=False)
    taskstartDate = models.DateField(blank=True, null=True)
    taskendDate = models.DateField(blank=True, null=True)
    taskFinished = models.DateField(blank=True, null=True)
    taskStatus = models.CharField(max_length=30, default='Not Started')
    taskFile = models.FileField(null=True, upload_to='files')
    nowDate = models.DateField(null=True, blank=True)

    def get_daysLeft(self):
        end = self.taskendDate
        curr = datetime.date.today()
        return (end-curr).days

    def in_progress_task(self):
        return Task.objects.filter(taskStatus='In Progress').count() / Task.objects.all().count()

    def not_started_task(self):
        return Task.objects.filter(taskStatus='Not Started').count()

    def delayed_task(self):
        return Task.objects.filter(taskendDate__lt=datetime.date.today(), taskStatus='Not Started').count() + \
               Task.objects.filter(taskendDate__lt=datetime.date.today(), taskStatus='In Progress').count()




class IncidentReport(models.Model):
    project = models.ForeignKey(Project, default='1', on_delete=models.CASCADE)
    milestone = models.ForeignKey(Milestone, default='1', on_delete=models.CASCADE)
    task = models.ForeignKey(Task, default='1', on_delete=models.CASCADE)
    category = models.CharField(max_length=1000)
    issueEncountered = models.CharField(max_length=1000)
    issueDescription = models.CharField(max_length=5000)
    issuePriority = models.CharField(max_length=20)
    dateEncountered = models.DateField()
    issueStatus = models.BooleanField(default=False)
    issueResolution = models.CharField(max_length=1000, default='N/A')
    nowDate = models.DateField()
    file = models.FileField(null=True, upload_to='files')
    resolvedBy = models.ForeignKey(User, default='1', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.issueEncountered



class ProjectContract(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    budget = models.DecimalField(max_digits=12, decimal_places=2)
    role = models.CharField(max_length=100)
    torNumber = models.IntegerField()
    objectives = models.TextField()
    approveDate = models.DateField(null=True)
    responsibleParty = models.CharField(max_length=200)
    status = models.CharField(max_length=100, default="For Review", blank=True)

    def __str__(self):
        return self.project.projectTitle

class ProjectExpense(models.Model):
    project = models.ForeignKey(Project, default='1', on_delete=models.CASCADE)
    expenseName = models.CharField(max_length=1000,null=True)
    expenseQuantity = models.CharField(max_length=10,null=True)
    expenseAmount = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    expenseTotal = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    expenseDate = models.CharField(max_length=20,null=True)
    expenseReceipt = models.FileField(null=True)



class Book(models.Model):

    name = models.CharField(max_length=255)
    isbn_number = models.CharField(max_length=13)

    class Meta:
        db_table = 'book'

    def __str__(self):
        return self.name

class Report(models.Model):
    reportTitle = models.CharField(max_length=50)
    datefrom = models.DateField(null=True)

sdrc/templates/sdrc/create_final_report.html
{% extends 'sdrc/base.html' %}

{% block content %}

    <div class="x_panel" style="height: 570px;">
        <div class="x_title">
            <h2>Upload Final Report</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i
                            class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Settings 1</a>
                        </li>
                        <li><a href="#">Settings 2</a>
                        </li>
                    </ul>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>


        <div class="x_content">

            {% if tasks and incidents %}
                <h4>You still have {{ tasks|length }} unfinished task/s and {{ incidents|length }} unresolved issue/s. You are only allowed to upload the final report once all issues has been solved and all tasks has been completed.</h4>
            {% elif incidents %}
                <h4>You still have {{ incidents|length }} unresolved issue/s. You are only allowed to upload the final report once all issues has been solved.</h4>
            {% elif tasks %}
                <h4>You still have {{ tasks|length }} unfinished tasks. You are only allowed to upload the final report once all tasks has been completed.</h4>
            {% else %}
                {% if project.finalReport %}
                    <h4>Final Report: <a href="{{ project.finalReport.url }}">File</a></h4>
                    <h4>Status: {{ project.status }}</h4>
                    <h4>Remarks: {{ project.remarks }}</h4>

                {% else %}
                    <h4>Upload final report here for approval of funding agency. Status of final report will be sent to your email. </h4>

                    <form method="POST" enctype="multipart/form-data" onsubmit="return submitAlert(event)">
                        {% csrf_token %}
                        <div class="form-group" style="margin-top: 40px; margin-left: 320px;">


                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <div class="btn-group">
                                    <input type="file" required=required name="finalReport" data-role="magic-overlay" data-target="#pictureBtn" data-edit="insertImage">
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary btn-md" style="margin-top: 20px;margin-left: 350px;">Upload</button>
                    </form>
                {% endif %}
            {% endif %}
        </div>
    </div>
    <script>
        function submitAlert(e){
            confirm('Final report successfully uploaded!')



        };
    </script>
{% endblock %}

sdrc/templates/sdrc/ganttchart.html
{% extends 'sdrc/base.html' %}
{% block content %}
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<div class="x_panel">
                  <div class="x_title">
                    <h2>Gantt Chart</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>



      <div class="x_content">

     <div id="chart_div" style="width: 900px; height: 400px;"></div>
      </div>
</div>



   <script>
      google.charts.load('current', {'packages':['gantt']});
    google.charts.setOnLoadCallback(drawChart);

    function drawChart() {

      var data = new google.visualization.DataTable();
      data.addColumn('string', 'Task ID');
      data.addColumn('string', 'Task Name');
      data.addColumn('string', 'Assigned To');
      data.addColumn('date', 'Start Date');
      data.addColumn('date', 'End Date');
      data.addColumn('number', 'Duration');
      data.addColumn('number', 'Percent Complete');
      data.addColumn('string', 'Dependencies');

      array = {{ array|safe }}



        for (var i = 0; i < {{ array|length }}; i++){
            var arr ={{ array|safe }}[0];

                var milestone = {{ array|safe }}[i][0]
                var name = milestone + ": " + {{ array|safe }}[i][1]

                var resource = {{ array|safe }}[i][2]



                 var selected_date_1 = {{ array|safe }}[i][3];


                 var selected_date_2 = {{ array|safe }}[i][4];
                 var status = {{ array|safe }}[i][5]


                 data.addRows([
                         [name,
                         name,
                         resource,
                         new Date(selected_date_1),
                         new Date(selected_date_2),
                         null,
                         status,
                         null]
                 ]);



        }

      var options = {
        height: 400,
        gantt: {
          trackHeight: 40,
          percentEnabled: false
        }
      };

      var chart = new google.visualization.Gantt(document.getElementById('chart_div'));

      chart.draw(data, options);
    }
</script>

{% endblock %}

sdrc/templates/sdrc/milestone_list.html
{% extends "sdrc/base.html" %}
{% block style %}
    <style>
        #hover:hover {

        }
    </style>

{% endblock %}

{% block title %} {% endblock %}

{% block content %}
    {% load humanize %}

        <div class="x_panel">

            <div class="x_title">
                <h3> Create Milestones</h3>
                <!--<b>NOTE:</b> <br>
                       *** You may click the name of the principal investigator to notify him or to send him an email <br>
                       *** You may click the issues under issues encountered column<br>
              <a href= ><button type="button" class="btn btn-success btn-sm"><span><i class="fa fa-plus-circle"></i></span> Add a New Project Budget</button></a> -->
                <ul class="nav navbar-right panel_toolbox">


                </ul>

            </div>
            <div class="x_content">
            <form id="form" class="form-horizontal form-label-left input_mask" method="POST">
            {% csrf_token %}
                 <div id="datatable-fixed-header_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                    <div class="row">
                        <div class="col-sm-6">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12"  style="height: 570px;">
                         <p class="text-muted font-13 m-b-30">
                         </p>

                                  <table id="datatable-fixed-header"
                                   class="table table-striped table-bordered dataTable no-footer" role="grid"
                                   aria-describedby="datatable-fixed-header_info">
                                <thead>

                                    <th class="sorting_asc" tabindex="0" aria-controls="datatable-fixed-header"
                                        rowspan="1" colspan="1" aria-sort="ascending"
                                        aria-label="Name: activate to sort column descending" style="width: 95px;">
                                        Project Name
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="datatable-fixed-header" rowspan="1"
                                        colspan="1" aria-label="Position: activate to sort column ascending"
                                        style="width: 139px;">Assigned To:
                                    </th>

                                    <th class="sorting_asc" tabindex="0" aria-controls="datatable-fixed-header"
                                        rowspan="1" colspan="1" aria-sort="ascending"
                                        aria-label="Name: activate to sort column descending" style="width: 95px;">
                                        Funding Agency's Name
                                    </th>
                                      <th class="sorting_asc" tabindex="0" aria-controls="datatable-fixed-header"
                                        rowspan="1" colspan="1" aria-sort="ascending"
                                        aria-label="Name: activate to sort column descending" style="width: 95px;">
                                        Project Overview
                                    </th>


                                     <th class="sorting_asc" tabindex="0" aria-controls="datatable-fixed-header"
                                        rowspan="1" colspan="1" aria-sort="ascending"
                                        aria-label="Name: activate to sort column descending" style="width: 95px;">
                                        Action
                                    </th>
                                </tr>
                                </thead>
                                      {% for project in projects %}
                                          {% if project.milestone_set.all %}

                                                  <tbody>
                                              <td>{{ project.projectTitle }}</td>
                                              <td>{{ project.principalInvestigator }}</td>
                                              <td>{{ project.fundingAgency }}</td>
                                              <td>{{ project.projectOverview }}</td>
                                               <td> <form method="POST">
                                     {% csrf_token %}<span> <input style="display: none" name="projectID" value={{ project.principalInvestigator_id }}>
                                     <button id="id_btn" type="submit" class="btn btn-primary create_btn">View Milestones</button>
                                    </span></form></td>



                                              {% else %}
                                                <td>{{ project.projectTitle }}</td>
                                        <td>{{ project.principalInvestigator }}</td>
                                        <td>{{ project.fundingAgency }}</td>
                                        <td>{{ project.projectOverview }}</td>

                                 <td> <form method="POST">
                                     {% csrf_token %}<span> <input style="display: none" name="projectID" value={{ project.principalInvestigator_id }}>
                                     <button id="id_btn" type="submit" class="btn btn-warning create_btn">Create Milestones</button>
                                    </span></form></td>
                                          {% endif %}

                                       </tbody>
                                      {% endfor %}
                                  </table>
                        </div>
                    </div>
                </div>
            </form>


            </div>
        </div>

<script>

result = document.querySelectorAll('.x_content .btn').length
view =  document.querySelectorAll('.x_content .view_btn').length


for(var i=0; i<result;i++){
     document.getElementById("projectID").setAttribute("id","projectID"+i)
    document.getElementsByClassName("create_btn")[i].setAttribute("id",i)

    $("#"+i).click(function () {

        $.ajax({
            url: "/budget-plan/",
            type: "POST",
            data:{
                projectID:document.getElementById("projectID"+this.id).value,
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            },
            success:function (response) {

             }

         })


    })
}


for(var i=0; i<view;i++){
     document.getElementById("projectID").setAttribute("id","projectID"+i)
    document.getElementsByClassName("view_btn")[i].setAttribute("id",i)

    $("#"+i).click(function () {

        $.ajax({
            url: "/budget-plan/",
            type: "POST",
            data:{
                projectID:document.getElementById("projectID"+this.id).value,
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            },
            success:function (response) {

             }

         })


    })
}





</script>

{% endblock %}

{% block script %}

{% endblock %}